group_name: planar_robot
pipeline_ids:
- dirrt
planner_ids:
  dirrt:
  - dirrt_paper
  #- mab_egreedy_adaptive_1
  #- mab_egreedy_adaptive_01
  - mab_egreedy_adaptive_99
  - mab_egreedy_adaptive_999
  - mab_uniform_volume
  - mab_uniform
  - mab_egreedy_10
  #- mab_ts
  #- mab_ts_bernoulli
  #- mab_egreedy_20_bernoulli

planning_time: 5.0
long_planning_time: 20.0 # first repetition planning time

queries_number: 2
query_prefix: cubes
scenarios: [maze_bitmap]
repetitions: 20
starting_query: 0

# scenarios
maze_bitmap:
  object_groups: ["maze"]
  query_0:
    goal_configurations:
    # - - 0.2
    #   - 0.25
     - - 0.2
       - 0.5
    # - - 0.2
    #   - 0.75
    # - - 0.22
    #   - 0.5
    # - - 0.22
    #   - 0.75
    # - - 0.18
    #   - 0.25
    # - - 0.18
    #   - 0.5
    # - - 0.21
    #   - 0.25
    # - - 0.21
    #   - 0.5
    # - - 0.21
    #   - 0.75
    # - - 0.19
    #   - 0.25
    # - - 0.19
    #   - 0.5
    # - - 0.19
    #   - 0.75
    # - - 0.17
    #   - 0.25
    # - - 0.17
    #   - 0.5
    # - - 0.17
    #   - 0.75
    # #- - 0.8
    # #  - 0.25
    # - - 0.8
    #   - 0.5
    # #- - 0.8
    # #  - 0.75
    start_configuration: [0.35, 0.5]

  query_1:
    goal_configurations:
    - - 0.2
      - 0.25
    - - 0.2
      - 0.5
    - - 0.2
      - 0.75
    - - 0.22
      - 0.25
    - - 0.22
      - 0.5
    - - 0.22
      - 0.75
    - - 0.18
      - 0.25
    - - 0.18
      - 0.5
    - - 0.21
      - 0.25
    - - 0.21
      - 0.5
    - - 0.21
      - 0.75
    - - 0.19
      - 0.25
    - - 0.19
      - 0.5
    - - 0.19
      - 0.75
    - - 0.17
      - 0.25
    - - 0.17
      - 0.5
    - - 0.17
      - 0.75
    - - 0.8
      - 0.5
    start_configuration: [0.55, 0.65]

maze_complex:
  object_groups: ["perimeter","maze_complex"]
  query_0:
    goal_configurations:
    - - 0.1
      - 0.1
    - - 0.9
      - 0.2
    - - 0.9
      - 0.9
    - - 0.1
      - 0.9
    start_configuration: [0.45, 0.45]

  query_1:
    goal_configurations:
    - - 0.08
      - 0.11
    - - 0.88
      - 0.102
    - - 0.91
      - 0.91
    - - 0.08
      - 0.91
    - - 0.1
      - 0.1
    - - 0.9
      - 0.1
    - - 0.9
      - 0.9
    - - 0.1
      - 0.9
    start_configuration: [0.45, 0.45]

  query_2:
    goal_configurations:
    - - 0.08
      - 0.11
    - - 0.88
      - 0.102
    - - 0.91
      - 0.91
    - - 0.08
      - 0.91
    - - 0.1
      - 0.1
    - - 0.9
      - 0.1
    - - 0.9
      - 0.9
    - - 0.1
      - 0.9
    - - 0.15
      - 0.1
    - - 0.85
      - 0.92
    - - 0.88
      - 0.88
    - - 0.13
      - 0.83
    - - 0.15
      - 0.15
    - - 0.8
      - 0.9
    - - 0.8
      - 0.8
    - - 0.1
      - 0.88
    start_configuration: [0.45, 0.45]

  query_3:
    goal_configurations:
    - - 0.08
      - 0.11
    - - 0.88
      - 0.102
    - - 0.91
      - 0.91
    - - 0.08
      - 0.91
    - - 0.1
      - 0.1
    - - 0.9
      - 0.1
    - - 0.9
      - 0.9
    - - 0.1
      - 0.9
    - - 0.15
      - 0.1
    - - 0.85
      - 0.92
    - - 0.88
      - 0.88
    - - 0.13
      - 0.83
    - - 0.15
      - 0.15
    - - 0.8
      - 0.9
    - - 0.8
      - 0.8
    - - 0.1
      - 0.88
    - - 0.0842
      - 0.1124
    - - 0.88232
      - 0.1432
    - - 0.9232
      - 0.93252
    - - 0.13523
      - 0.9352
    - - 0.2523
      - 0.22523
    - - 0.8823
      - 0.1342
    - - 0.922
      - 0.92432
    - - 0.13253
      - 0.923
    - - 0.13242
      - 0.12532
    - - 0.82532
      - 0.92352
    - - 0.8523
      - 0.82532
    - - 0.1235
      - 0.823
    - - 0.1253
      - 0.123
    - - 0.7623
      - 0.952
    - - 0.52
      - 0.89232
    - - 0.222
      - 0.84
    start_configuration: [0.45, 0.45]


maze_easy:
  object_groups: ["perimeter","maze_easy"]
  query_0:
    goal_configurations:
    - - 0.15
      - 0.15
    - - 0.15
      - 0.85
    - - 0.85
      - 0.15
    - - 0.85
      - 0.85
    start_configuration: [0.35, 0.7]

  query_1:
    goal_configurations:
    - - 0.08
      - 0.11
    - - 0.88
      - 0.102
    - - 0.91
      - 0.91
    - - 0.08
      - 0.91
    - - 0.1
      - 0.1
    - - 0.9
      - 0.1
    - - 0.9
      - 0.9
    - - 0.1
      - 0.9
    start_configuration: [0.45, 0.45]

  query_2:
    goal_configurations:
    - - 0.08
      - 0.11
    - - 0.88
      - 0.102
    - - 0.91
      - 0.91
    - - 0.08
      - 0.91
    - - 0.1
      - 0.1
    - - 0.9
      - 0.1
    - - 0.9
      - 0.9
    - - 0.1
      - 0.9
    - - 0.15
      - 0.1
    - - 0.85
      - 0.92
    - - 0.88
      - 0.88
    - - 0.13
      - 0.83
    - - 0.15
      - 0.15
    - - 0.8
      - 0.9
    - - 0.8
      - 0.8
    - - 0.1
      - 0.88
    start_configuration: [0.45, 0.45]

  query_3:
    goal_configurations:
    - - 0.08
      - 0.11
    - - 0.88
      - 0.102
    - - 0.91
      - 0.91
    - - 0.08
      - 0.91
    - - 0.1
      - 0.1
    - - 0.9
      - 0.1
    - - 0.9
      - 0.9
    - - 0.1
      - 0.9
    - - 0.15
      - 0.1
    - - 0.85
      - 0.92
    - - 0.88
      - 0.88
    - - 0.13
      - 0.83
    - - 0.15
      - 0.15
    - - 0.8
      - 0.9
    - - 0.8
      - 0.8
    - - 0.1
      - 0.88
    - - 0.0842
      - 0.1124
    - - 0.88232
      - 0.1432
    - - 0.9232
      - 0.93252
    - - 0.13523
      - 0.9352
    - - 0.2523
      - 0.22523
    - - 0.8823
      - 0.1342
    - - 0.922
      - 0.92432
    - - 0.13253
      - 0.923
    - - 0.13242
      - 0.12532
    - - 0.82532
      - 0.92352
    - - 0.8523
      - 0.82532
    - - 0.1235
      - 0.823
    - - 0.1253
      - 0.123
    - - 0.7623
      - 0.952
    - - 0.52
      - 0.89232
    - - 0.222
      - 0.84
    start_configuration: [0.45, 0.45]
