planner_names_map:
  dirrt_paper               : dirrt_paper
  mab_egreedy_adaptive_999  : mab_egreedy_adaptive_999
  mab_egreedy_adaptive_999  : mab_egreedy_adaptive_999
  mab_uniform_volume        : mab_uniform_volume
  mab_uniform               : mab_uniform
  mab_egreedy_10            : mab_egreedy_10
  # mab_ts                    : mab_ts

boxplot_planning_times: [0.05, 0.1, 0.5, 1.0]
axis_xlim: 0.2
