#csv_name: /home/marco/.ros/test_mab_2d/test/test_res.csv
#csv_name: /home/marco/.ros/test_mab_2d/maze_many_passages/test_2d_scenarios_maze_many_passages.csv
#csv_name: /home/marco/.ros/test_mab_2d/maze_narrow_passage/test_2d_scenarios_maze_narrow_passage.csv
#csv_name: /home/marco/.ros/test_mab_2d/maze_infeasible_passage/test_2d_scenarios_maze_infeasible_passage.csv
#csv_name: /home/marco/.ros/test_mab_2d/maze_infeasible_passage_but_one/test_2d_scenarios_maze_infeasible_passage_but_one.csv
#csv_name: /home/marco/.ros/test_mab_2d/maze_complex/test_2d_scenarios_res_complex.csv
#csv_name: /home/marco/.ros/test_mab_2d/maze_medium/test_2d_scenarios_medium.csv
#csv_name: /home/marco/.ros/test_mab_2d/maze_easy/test_2d_scenarios_easy.csv
csv_name: /home/marco/.ros/test_mab_2d/test_2d_scenarios_appended_all.csv

figure_folder: /home/marco/.ros

planner_names_map:
  mixed_strategy_a: mixed_strategy_a
  mixed_strategy_b: mixed_strategy_b
  informed_rrt: informed_rrt
  warp_strategy: warp_strategy

plot_only_map_names: false

boxplot_planning_times: [0.1, 0.2,  0.3]
axis_xlim: 2.0 # plots
#axis_ylim: 2.0 # boxplots
