group_name: planar_robot
pipeline_ids:
- dirrt
planner_ids:
  dirrt:
  #- mixed_strategy_a
  #- mixed_strategy_b
  #- informed_rrt
  ##- warp_strategy
  #- mab_uniform
  #- mab_uniform_volume
  #- mab_ts_bernoulli
  #- mab_ucb1_bernoulli
  - mab_egreedy_eps_decreasing_bernoulli
  #- mab_ts_bernoulli_sw_1
  #- mab_ts_bernoulli_sw_2
  #- mab_ts_bernoulli_gain_1
  #- mab_ts_bernoulli_gain_2

planning_time: 0.3
long_planning_time:  2.0 # first repetition planning time

queries_number: 2
query_prefix: test_2d
#scenarios: [maze_many_passages, maze_narrow_passage, maze_infeasible_passage, maze_infeasible_passage_but_one, maze_complex, maze_medium, maze_easy]
scenarios: [maze_many_passages] 
repetitions: 20
starting_query: 1
sampling_time: 0.1

# scenarios
empty:
  object_groups: []
  query_0:
    goal_configurations:
    - [0.9, 0.9]
    start_configuration: [0.1, 0.1]
  query_1:
    goal_configurations:
    - [0.85, 0.95]
    start_configuration: [0.1, 0.1]
    
maze_many_passages:
  object_groups: ["maze_many_passages"]
  query_0:
    goal_configurations:
    - - 0.1
      - 0.1
    - - 0.1
      - 0.9
    - - 0.9
      - 0.1
    - - 0.9
      - 0.9
    start_configuration: [0.5, 0.5]

  query_1:
    goal_configurations:
    - - 0.1
      - 0.1
    - - 0.1
      - 0.9
    - - 0.9
      - 0.1
    - - 0.9
      - 0.9
    - - 0.15
      - 0.5
    - - 0.85
      - 0.5 
    start_configuration: [0.5, 0.5]

  query_2:
    goal_configurations:
    - - 0.2
      - 0.25
    - - 0.2
      - 0.5
    - - 0.2
      - 0.75
    - - 0.22
      - 0.5
    - - 0.22
      - 0.75
    - - 0.18
      - 0.25
    - - 0.18
      - 0.5
    - - 0.21
      - 0.25
    - - 0.21
      - 0.5
    - - 0.21
      - 0.75
    - - 0.19
      - 0.25
    - - 0.19
      - 0.5
    - - 0.19
      - 0.75
    - - 0.17
      - 0.25
    - - 0.17
      - 0.5
    - - 0.17
      - 0.75
    - - 0.8
      - 0.25
    - - 0.8
      - 0.5
    - - 0.8
      - 0.75
    # start_configuration: [0.35, 0.5]
    start_configuration: [0.35, 0.93]

  query_3:
    goal_configurations:
    - - 0.2
      - 0.25
    - - 0.2
      - 0.5
    - - 0.2
      - 0.75
    - - 0.22
      - 0.25
    - - 0.22
      - 0.5
    - - 0.22
      - 0.75
    - - 0.18
      - 0.25
    - - 0.18
      - 0.5
    - - 0.21
      - 0.25
    - - 0.21
      - 0.5
    - - 0.21
      - 0.75
    - - 0.19
      - 0.25
    - - 0.19
      - 0.5
    - - 0.19
      - 0.75
    - - 0.17
      - 0.25
    - - 0.17
      - 0.5
    - - 0.17
      - 0.75
    - - 0.8
      - 0.5
    # start_configuration: [0.55, 0.65]
    start_configuration: [0.35, 0.93]

maze_narrow_passage:
  object_groups: ["maze_narrow_passage"]
  query_0:
    goal_configurations:
    - - 0.2
      - 0.25
    - - 0.2
      - 0.5
    - - 0.2
      - 0.75
    - - 0.22
      - 0.5
    - - 0.22
      - 0.75
    - - 0.18
      - 0.25
    - - 0.18
      - 0.5
    - - 0.21
      - 0.25
    - - 0.21
      - 0.5
    - - 0.21
      - 0.75
    - - 0.19
      - 0.25
    - - 0.19
      - 0.5
    - - 0.19
      - 0.75
    - - 0.17
      - 0.25
    - - 0.17
      - 0.5
    - - 0.17
      - 0.75
    - - 0.8
      - 0.25
    - - 0.8
      - 0.5
    - - 0.8
      - 0.75
    # start_configuration: [0.35, 0.5]
    start_configuration: [0.78, 0.93]

  query_1:
    goal_configurations:
    - - 0.2
      - 0.25
    - - 0.2
      - 0.5
    - - 0.2
      - 0.75
    - - 0.22
      - 0.25
    - - 0.22
      - 0.5
    - - 0.22
      - 0.75
    - - 0.18
      - 0.25
    - - 0.18
      - 0.5
    - - 0.21
      - 0.25
    - - 0.21
      - 0.5
    - - 0.21
      - 0.75
    - - 0.19
      - 0.25
    - - 0.19
      - 0.5
    - - 0.19
      - 0.75
    - - 0.17
      - 0.25
    - - 0.17
      - 0.5
    - - 0.17
      - 0.75
    - - 0.8
      - 0.5
    # start_configuration: [0.55, 0.65]
    start_configuration: [0.78, 0.93]
  query_2:
    goal_configurations:
    - - 0.2
      - 0.25
    - - 0.2
      - 0.5
    - - 0.2
      - 0.75
    - - 0.22
      - 0.5
    - - 0.22
      - 0.75
    - - 0.18
      - 0.25
    - - 0.18
      - 0.5
    - - 0.21
      - 0.25
    - - 0.21
      - 0.5
    - - 0.21
      - 0.75
    - - 0.19
      - 0.25
    - - 0.19
      - 0.5
    - - 0.19
      - 0.75
    - - 0.17
      - 0.25
    - - 0.17
      - 0.5
    - - 0.17
      - 0.75
    - - 0.8
      - 0.25
    - - 0.8
      - 0.5
    - - 0.8
      - 0.75
    # start_configuration: [0.35, 0.5]
    start_configuration: [0.35, 0.93]

  query_3:
    goal_configurations:
    - - 0.2
      - 0.25
    - - 0.2
      - 0.5
    - - 0.2
      - 0.75
    - - 0.22
      - 0.25
    - - 0.22
      - 0.5
    - - 0.22
      - 0.75
    - - 0.18
      - 0.25
    - - 0.18
      - 0.5
    - - 0.21
      - 0.25
    - - 0.21
      - 0.5
    - - 0.21
      - 0.75
    - - 0.19
      - 0.25
    - - 0.19
      - 0.5
    - - 0.19
      - 0.75
    - - 0.17
      - 0.25
    - - 0.17
      - 0.5
    - - 0.17
      - 0.75
    - - 0.8
      - 0.5
    # start_configuration: [0.55, 0.65]
    start_configuration: [0.33, 0.5]

maze_infeasible_passage:
  object_groups: ["maze_infeasible_passage"]
  query_0:
    goal_configurations:
    - - 0.68
      - 0.64
    - - 0.12
      - 0.12
    - - 0.13
      - 0.13
    - - 0.11
      - 0.11
    - - 0.14
      - 0.14
    - - 0.25
      - 0.75
    - - 0.23
      - 0.83
    - - 0.121
      - 0.121
    - - 0.131
      - 0.131
    - - 0.111
      - 0.111
    - - 0.141
      - 0.141
    - - 0.122
      - 0.122
    - - 0.132
      - 0.132
    - - 0.112
      - 0.112
    - - 0.142
      - 0.142
    - - 0.252
      - 0.752
    - - 0.232
      - 0.833
    - - 0.122
      - 0.122
    - - 0.132
      - 0.132
    - - 0.112
      - 0.101
    - - 0.13
      - 0.13
    # start_configuration: [0.35, 0.5]
    start_configuration: [0.33, 0.5]

  query_1:
    goal_configurations:
    - - 0.2
      - 0.25
    - - 0.2
      - 0.5
    - - 0.2
      - 0.75
    - - 0.22
      - 0.25
    - - 0.22
      - 0.5
    - - 0.22
      - 0.75
    - - 0.18
      - 0.25
    - - 0.18
      - 0.5
    - - 0.21
      - 0.25
    - - 0.21
      - 0.5
    - - 0.21
      - 0.75
    - - 0.19
      - 0.25
    - - 0.19
      - 0.5
    - - 0.19
      - 0.75
    - - 0.17
      - 0.25
    - - 0.17
      - 0.5
    - - 0.17
      - 0.75
    - - 0.8
      - 0.5
    # start_configuration: [0.55, 0.65]
    start_configuration: [0.35, 0.07]
  query_2:
    goal_configurations:
    - - 0.2
      - 0.25
    - - 0.2
      - 0.5
    - - 0.2
      - 0.75
    - - 0.22
      - 0.5
    - - 0.22
      - 0.75
    - - 0.18
      - 0.25
    - - 0.18
      - 0.5
    - - 0.21
      - 0.25
    - - 0.21
      - 0.5
    - - 0.21
      - 0.75
    - - 0.19
      - 0.25
    - - 0.19
      - 0.5
    - - 0.19
      - 0.75
    - - 0.17
      - 0.25
    - - 0.17
      - 0.5
    - - 0.17
      - 0.75
    - - 0.8
      - 0.25
    - - 0.8
      - 0.5
    - - 0.8
      - 0.75
    # start_configuration: [0.35, 0.5]
    start_configuration: [0.35, 0.45]

  query_3:
    goal_configurations:
    - - 0.2
      - 0.25
    - - 0.2
      - 0.5
    - - 0.2
      - 0.75
    - - 0.22
      - 0.25
    - - 0.22
      - 0.5
    - - 0.22
      - 0.75
    - - 0.18
      - 0.25
    - - 0.18
      - 0.5
    - - 0.21
      - 0.25
    - - 0.21
      - 0.5
    - - 0.21
      - 0.75
    - - 0.19
      - 0.25
    - - 0.19
      - 0.5
    - - 0.19
      - 0.75
    - - 0.17
      - 0.25
    - - 0.17
      - 0.5
    - - 0.17
      - 0.75
    - - 0.8
      - 0.5
    # start_configuration: [0.55, 0.65]
    start_configuration: [0.35, 0.17]

maze_infeasible_passage_but_one:
  object_groups: ["maze_infeasible_passage_but_one"]
  query_0:
    goal_configurations:
    - - 0.68
      - 0.64
    - - 0.92
      - 0.12
    - - 0.12
      - 0.12
    - - 0.13
      - 0.13
    - - 0.11
      - 0.11
    - - 0.14
      - 0.14
    - - 0.121
      - 0.121
    - - 0.131
      - 0.131
    - - 0.111
      - 0.111
    - - 0.141
      - 0.141
    start_configuration: [0.33, 0.5]
  query_1:
    goal_configurations:
    - - 0.67
      - 0.63
    - - 0.12
      - 0.12
    - - 0.13
      - 0.13
    - - 0.11
      - 0.11
    - - 0.14
      - 0.14
    - - 0.12
      - 0.92
    - - 0.13
      - 0.93
    - - 0.11
      - 0.91
    - - 0.14
      - 0.94
    - - 0.121
      - 0.121
    - - 0.131
      - 0.131
    - - 0.111
      - 0.111
    - - 0.141
      - 0.141
    - - 0.121
      - 0.921
    - - 0.131
      - 0.931
    - - 0.111
      - 0.911
    - - 0.141
      - 0.941
    start_configuration: [0.35, 0.48]

maze_complex:
  object_groups: ["perimeter","maze_complex"]
  query_0:
    goal_configurations:
    - - 0.8
      - 0.8
    - - 0.9
      - 0.9
    - - 0.8
      - 0.9
    - - 0.9
      - 0.8
    - - 0.75
      - 0.05
    - - 0.75
      - 0.32
    - - 0.01
      - 0.67
    start_configuration: [0.64, 0.64]

  query_1:
    goal_configurations:
    - - 0.08
      - 0.11
    - - 0.88
      - 0.99
    - - 0.91
      - 0.91
    - - 0.08
      - 0.91
    - - 0.1
      - 0.1
    - - 0.901
      - 0.1
    - - 0.902
      - 0.9
    - - 0.1
      - 0.903
    start_configuration: [0.45, 0.45]

  query_2:
    goal_configurations:
    - - 0.08
      - 0.11
    - - 0.88
      - 0.102
    - - 0.91
      - 0.91
    - - 0.08
      - 0.91
    - - 0.1
      - 0.1
    - - 0.9
      - 0.1
    - - 0.9
      - 0.9
    - - 0.1
      - 0.9
    - - 0.15
      - 0.1
    - - 0.85
      - 0.92
    - - 0.88
      - 0.88
    - - 0.13
      - 0.83
    - - 0.15
      - 0.15
    - - 0.8
      - 0.9
    - - 0.8
      - 0.8
    - - 0.1
      - 0.88
    start_configuration: [0.45, 0.45]

  query_3:
    goal_configurations:
    - - 0.08
      - 0.11
    - - 0.88
      - 0.102
    - - 0.91
      - 0.91
    - - 0.08
      - 0.91
    - - 0.1
      - 0.1
    - - 0.9
      - 0.1
    - - 0.9
      - 0.9
    - - 0.1
      - 0.9
    - - 0.15
      - 0.1
    - - 0.85
      - 0.92
    - - 0.88
      - 0.88
    - - 0.13
      - 0.83
    - - 0.15
      - 0.15
    - - 0.8
      - 0.9
    - - 0.8
      - 0.8
    - - 0.1
      - 0.88
    - - 0.0842
      - 0.1124
    - - 0.88232
      - 0.1432
    - - 0.9232
      - 0.93252
    - - 0.13523
      - 0.9352
    - - 0.2523
      - 0.22523
    - - 0.8823
      - 0.1342
    - - 0.922
      - 0.92432
    - - 0.13253
      - 0.923
    - - 0.13242
      - 0.12532
    - - 0.82532
      - 0.92352
    - - 0.8523
      - 0.82532
    - - 0.1235
      - 0.823
    - - 0.1253
      - 0.123
    - - 0.7623
      - 0.952
    - - 0.52
      - 0.89232
    - - 0.222
      - 0.84
    start_configuration: [0.45, 0.45]

maze_medium:
  object_groups: ["perimeter","maze_medium"]
  query_0:
    goal_configurations:
    - - 0.1
      - 0.1
    - - 0.2
      - 0.9
    - - 0.85
      - 0.9
    - - 0.85
      - 0.2
    start_configuration: [0.5, 0.5]
  query_1:
    goal_configurations:
    - - 0.1
      - 0.1
    - - 0.2
      - 0.9
    - - 0.85
      - 0.2
    - - 0.12
      - 0.08
    - - 0.8
      - 0.25
    - - 0.77
      - 0.22
    start_configuration: [0.8, 0.9]

maze_easy:
  object_groups: ["perimeter","maze_easy"]
  query_0:
    goal_configurations:
    - - 0.15
      - 0.15
    - - 0.15
      - 0.85
    - - 0.85
      - 0.15
    - - 0.85
      - 0.85
    start_configuration: [0.35, 0.7]

  query_1:
    goal_configurations:
    - - 0.08
      - 0.11
    - - 0.88
      - 0.102
    - - 0.91
      - 0.91
    - - 0.08
      - 0.91
    - - 0.1
      - 0.1
    - - 0.9
      - 0.1
    - - 0.9
      - 0.9
    - - 0.1
      - 0.9
    start_configuration: [0.45, 0.45]

  query_2:
    goal_configurations:
    - - 0.08
      - 0.11
    - - 0.88
      - 0.102
    - - 0.91
      - 0.91
    - - 0.08
      - 0.91
    - - 0.1
      - 0.1
    - - 0.9
      - 0.1
    - - 0.9
      - 0.9
    - - 0.1
      - 0.9
    - - 0.15
      - 0.1
    - - 0.85
      - 0.92
    - - 0.88
      - 0.88
    - - 0.13
      - 0.83
    - - 0.15
      - 0.15
    - - 0.8
      - 0.9
    - - 0.8
      - 0.8
    - - 0.1
      - 0.88
    start_configuration: [0.45, 0.45]

  query_3:
    goal_configurations:
    - - 0.08
      - 0.11
    - - 0.88
      - 0.102
    - - 0.91
      - 0.91
    - - 0.08
      - 0.91
    - - 0.1
      - 0.1
    - - 0.9
      - 0.1
    - - 0.9
      - 0.9
    - - 0.1
      - 0.9
    - - 0.15
      - 0.1
    - - 0.85
      - 0.92
    - - 0.88
      - 0.88
    - - 0.13
      - 0.83
    - - 0.15
      - 0.15
    - - 0.8
      - 0.9
    - - 0.8
      - 0.8
    - - 0.1
      - 0.88
    - - 0.0842
      - 0.1124
    - - 0.88232
      - 0.1432
    - - 0.9232
      - 0.93252
    - - 0.13523
      - 0.9352
    - - 0.2523
      - 0.22523
    - - 0.8823
      - 0.1342
    - - 0.922
      - 0.92432
    - - 0.13253
      - 0.923
    - - 0.13242
      - 0.12532
    - - 0.82532
      - 0.92352
    - - 0.8523
      - 0.82532
    - - 0.1235
      - 0.823
    - - 0.1253
      - 0.123
    - - 0.7623
      - 0.952
    - - 0.52
      - 0.89232
    - - 0.222
      - 0.84
    start_configuration: [0.45, 0.45]
