group_name: planar2robots
pipeline_ids:
- dirrt
planner_ids:
  dirrt:
  #- mixed_strategy_a
  #- informed_rrt
  #- mab_ts_bernoulli
  #- mab_uniform
  #- mab_uniform_volume
  #- mab_egreedy_eps_decreasing_bernoulli
  #- mab_egreedy_best_cost 
  - mab_ts_best_cost 
  #- mab_ts_best_cost_09999 

planning_time: 2.0
long_planning_time:  5.0 # first repetition planning time

queries_number: 1
query_prefix: test_2d
#scenarios: [maze_many_passages, maze_narrow_passage, maze_infeasible_passage, maze_infeasible_passage_but_one, maze_complex, maze_medium, maze_easy]
scenarios: [maze_complex] 
repetitions: 20
starting_query: 0
starting_repetition: 0
sampling_time: 0.5

# scenarios
    
maze_complex:
  object_groups: ["maze_complex","perimeter"]
  query_0:
    goal_configurations:
    - [0.1, 0.1, 0.1, 0.9]
    - [0.1, 0.1, 0.9, 0.9]
    - [0.1, 0.1, 0.9, 0.1]
    - [0.1, 0.9, 0.1, 0.1]
    - [0.1, 0.9, 0.9, 0.9]
    - [0.1, 0.9, 0.9, 0.1]
    - [0.9, 0.9, 0.1, 0.1]
    - [0.9, 0.9, 0.1, 0.9]
    - [0.9, 0.9, 0.9, 0.1]
    - [0.9, 0.1, 0.1, 0.1]
    - [0.9, 0.1, 0.1, 0.9]
    - [0.9, 0.1, 0.9, 0.9]
    start_configuration: [0.45,0.5,0.55,0.5]



maze_medium:
  object_groups: ["maze_medium","perimeter"]
  query_0:
    goal_configurations:
    - [0.1, 0.1, 0.1, 0.9]
    - [0.1, 0.1, 0.9, 0.9]
    - [0.1, 0.1, 0.9, 0.1]
    - [0.1, 0.9, 0.1, 0.1]
    - [0.1, 0.9, 0.9, 0.9]
    - [0.1, 0.9, 0.9, 0.1]
    - [0.9, 0.9, 0.1, 0.1]
    - [0.9, 0.9, 0.1, 0.9]
    - [0.9, 0.9, 0.9, 0.1]
    - [0.9, 0.1, 0.1, 0.1]
    - [0.9, 0.1, 0.1, 0.9]
    - [0.9, 0.1, 0.9, 0.9]
    start_configuration: [0.4,0.5,0.6,0.5]
