maze_txt:
- frame: world
  position:
  - 0.1
  - 0.9
  - 0.0
  quaternion:
  - 0
  - 0
  - 0
  - 1
  type: box_200x200mm
- frame: world
  position:
  - 0.5
  - 0.9
  - 0.0
  quaternion:
  - 0
  - 0
  - 0
  - 1
  type: box_200x200mm
- frame: world
  position:
  - 0.7000000000000001
  - 0.9
  - 0.0
  quaternion:
  - 0
  - 0
  - 0
  - 1
  type: box_200x200mm
- frame: world
  position:
  - 0.1
  - 0.7
  - 0.0
  quaternion:
  - 0
  - 0
  - 0
  - 1
  type: box_200x200mm
- frame: world
  position:
  - 0.5
  - 0.7
  - 0.0
  quaternion:
  - 0
  - 0
  - 0
  - 1
  type: box_200x200mm
- frame: world
  position:
  - 0.7000000000000001
  - 0.7
  - 0.0
  quaternion:
  - 0
  - 0
  - 0
  - 1
  type: box_200x200mm
- frame: world
  position:
  - 0.1
  - 0.29999999999999993
  - 0.0
  quaternion:
  - 0
  - 0
  - 0
  - 1
  type: box_200x200mm
- frame: world
  position:
  - 0.30000000000000004
  - 0.29999999999999993
  - 0.0
  quaternion:
  - 0
  - 0
  - 0
  - 1
  type: box_200x200mm
- frame: world
  position:
  - 0.5
  - 0.29999999999999993
  - 0.0
  quaternion:
  - 0
  - 0
  - 0
  - 1
  type: box_200x200mm
- frame: world
  position:
  - 0.7000000000000001
  - 0.29999999999999993
  - 0.0
  quaternion:
  - 0
  - 0
  - 0
  - 1
  type: box_200x200mm
- frame: world
  position:
  - 0.5
  - 0.09999999999999998
  - 0.0
  quaternion:
  - 0
  - 0
  - 0
  - 1
  type: box_200x200mm
scene_autogenerated_on: 11/28/2023, 11:18:53
