level0_hw:
  remap_source_args:
  - "/level0_hw/js_pub/joint_states"
  remap_target_args:
  - "/planar_cartesian_robot_controller/joint_states"

  js_pub:
    type: cnr/control/JointStatePublisher
    controlled_joint: all
    base_link: world
    tool_link: end_effector
    robot_description_param: /robot_description
    robot_description_planning_param: /robot_description_planning

  ctrl1:
    type: "cnr/control/OpenLoopPosVelController"
    setpoint_topic_name: "/planar_cartesian_robot_controller/joint_target"
    controlled_joints: all
    enable_setpoint_watchdog: false

#  microinterpolator:
#    type: "cnr/control/ScaledFJTPosVelEffController"
#    controlled_joints: all
#    continuity_order: 1
#    continuity_order: 1
#    goal_tolerance: 0.0001 # optional (default=0.001). it you be a scalar or any array with a value for each joint
#    #path_tolerance: 0.001 # optional (default=0.001). it you be a scalar or any array with a value for each joint
#    check_tolerance: true # optional (default=true). if true, goal ends when the joint states and targets are in tolerance. Use false
#    pub_log_target: true
