group_names_map:
  mixed_strategy_a: planar_robot
  mixed_strategy_b: planar_robot
  informed_rrt: planar_robot
  warp_strategy: planar_robot
  # timebased: planar_robot
  #
  mab_uniform:  planar_robot
  mab_uniform_volume: planar_robot
  mab_ts_bernoulli: planar_robot
  mab_egreedy_eps_decreasing_bernoulli: planar_robot
  mab_ucb1_bernoulli: planar_robot
  # timebased:                     manipulator
  mab_egreedy_adaptive_reward_eps_decreasing_b1: planar_robot
  mab_egreedy_adaptive_reward_eps_decreasing_b2: planar_robot
  mab_egreedy_adaptive_reward_eps_decreasing_b3: planar_robot
  mab_egreedy_adaptive_reward_eps_decreasing_b4: planar_robot
  mab_ts_bernoulli_gain_1: planar_robot
  mab_ts_bernoulli_gain_2: planar_robot
  mab_ts_bernoulli_sw_1: planar_robot
  mab_ts_bernoulli_sw_2: planar_robot

default_planner_config: informed_rrt

mixed_strategy_a:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  rewire_radius: 0.05
  extend: true
  local_bias: 0.25
  forgetting_factor: 0.999
  tube_radius: 0.02
  utopia_tolerance: 0.0000001
  collision_distance: 0.001

mixed_strategy_b:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  rewire_radius: 0.1
  extend: true
  local_bias: 0.25
  forgetting_factor: 0.999
  tube_radius: 0.02
  utopia_tolerance: 0.0000001
  collision_distance: 0.001
  
warp_strategy:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  rewire_radius: 0.05
  extend: true
  local_bias: 0.25
  forgetting_factor: 0.000001
  tube_radius: 0.02
  informed: false
  warp: true
  utopia_tolerance: 0.0000001
  collision_distance: 0.001
  
informed_rrt:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  rewire_radius: 0.05
  extend: true
  local_bias: 0.0
  forgetting_factor: 0
  tube_radius: 0.01
  utopia_tolerance: 0.0000001
  collision_distance: 0.001
  #display_tree: true
  #display_tree_period: 0.1
  #display_flag: true
  
mab_uniform:
  type: Multigoal
  inherit_from: informed_rrt
  policy_type: MultiArmedBandit
  policy_name: PolicyUniformOnGoals

mab_uniform_volume:
  type: Multigoal
  inherit_from: informed_rrt
  policy_type: MultiArmedBandit
  policy_name: PolicyUniformOnVolume
  
mab_ts_bernoulli:
  type: Multigoal
  inherit_from: informed_rrt
  policy_type: MultiArmedBandit
  policy_name: Thomson
  reward_fcn: Bernoulli

mab_ts_bernoulli_gain_1:
  type: Multigoal
  inherit_from: informed_rrt
  policy_type: MultiArmedBandit
  policy_name: Thomson
  reward_fcn: Bernoulli
  reward_gain: 10.0

mab_ts_bernoulli_gain_2:
  type: Multigoal
  inherit_from: informed_rrt
  policy_type: MultiArmedBandit
  policy_name: Thomson
  reward_fcn: Bernoulli
  reward_gain: 100.0

mab_ts_bernoulli_sw_1:
  type: Multigoal
  inherit_from: informed_rrt
  policy_type: MultiArmedBandit
  policy_name: Thomson
  reward_fcn: Bernoulli
  reward_gain: 1.0
  mab_forgetting_factor: 0.01

mab_ts_bernoulli_sw_2:
  type: Multigoal
  inherit_from: informed_rrt
  policy_type: MultiArmedBandit
  policy_name: Thomson
  reward_fcn: Bernoulli
  reward_gain: 1.0
  mab_forgetting_factor: 0.005

mab_ucb1_bernoulli:
  type: Multigoal
  inherit_from: informed_rrt
  policy_type: MultiArmedBandit
  policy_name: UCB1
  reward_fcn: Bernoulli




timebased:
  type: TimeBasedMultigoal
  max_distance: 0.2
  max_refine_time: 1500.0
  extend: false
  local_bias: 0.0
  tube_radius: 0.02
  collision_distance: 0.001

mab_egreedy_20:
  type: Multigoal
  inherit_from: informed_rrt
  policy_type: MultiArmedBandit
  policy_name: eGreedy
  epsilon_coef: 0.2

mab_egreedy_adaptive_reward:
  type: Multigoal
  inherit_from: mab_egreedy_20
  egreedy_reward_forgetting_factor: 0.05
  
mab_egreedy_adaptive_reward_bernoulli:
  type: Multigoal
  inherit_from: mab_egreedy_20
  egreedy_reward_forgetting_factor: 0.05
  reward_fcn: Bernoulli
  
mab_egreedy_adaptive_eps:
  type: Multigoal
  inherit_from: mab_egreedy_20
  egreedy_forgetting_factor: 0.01
  
mab_egreedy_adaptive_eps_bernoulli:
  type: Multigoal
  inherit_from: mab_egreedy_20
  egreedy_forgetting_factor: 0.01
  reward_fcn: Bernoulli

mab_egreedy_adaptive_reward_eps:
  type: Multigoal
  inherit_from: mab_egreedy_20
  egreedy_reward_forgetting_factor: 0.05
  egreedy_forgetting_factor: 0.01
  epsilon_coef: 1.0

mab_egreedy_eps_decreasing:
  type: Multigoal
  inherit_from: mab_egreedy_20
  epsilon_exp: 0.999
  epsilon_coef: 1.0

mab_egreedy_eps_decreasing_bernoulli:
  type: Multigoal
  inherit_from: mab_egreedy_20
  epsilon_exp: 0.999
  reward_fcn: Bernoulli
  epsilon_coef: 1.0
  
mab_egreedy_adaptive_reward_eps_decreasing_b1:
  type: Multigoal
  inherit_from: mab_egreedy_eps_decreasing_bernoulli
  egreedy_reward_forgetting_factor: 0.01
  
mab_egreedy_adaptive_reward_eps_decreasing_b2:
  type: Multigoal
  inherit_from: mab_egreedy_eps_decreasing_bernoulli
  egreedy_reward_forgetting_factor: 0.005

mab_egreedy_adaptive_reward_eps_decreasing_b3:
  type: Multigoal
  inherit_from: mab_egreedy_eps_decreasing_bernoulli
  egreedy_reward_forgetting_factor: 0.05
  
mab_egreedy_adaptive_reward_eps_decreasing_b4:
  type: Multigoal
  inherit_from: mab_egreedy_eps_decreasing_bernoulli
  egreedy_reward_forgetting_factor: 0.001

mab_egreedy_20_best:
  type: Multigoal
  inherit_from: mab_egreedy_20
  reward_fcn: BestCost

mab_egreedy_ws:
  type: Multigoal
  inherit_from: mab_egreedy_20
  warm_start_reward: true




