group_names_map:
  mixed_strategy_a: planar4robots
  informed_rrt: planar4robots
  mab_ts_bernoulli: planar4robots
  mab_uniform: planar4robots
  mab_uniform_volume: planar4robots

default_planner_config: informed_rrt

mixed_strategy_a:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  rewire_radius: 0.05
  extend: false
  local_bias: 0.25
  forgetting_factor: 0.999
  tube_radius: 0.02
  utopia_tolerance: 0.0000001
  collision_distance: 0.001
  
informed_rrt:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  rewire_radius: 0.05
  extend: true
  local_bias: 0.0
  forgetting_factor: 0
  tube_radius: 0.01
  utopia_tolerance: 0.0000001
  collision_distance: 0.001

mab_uniform:
  type: Multigoal
  inherit_from: informed_rrt
  policy_type: MultiArmedBandit
  policy_name: PolicyUniformOnGoals

mab_uniform_volume:
  type: Multigoal
  inherit_from: informed_rrt
  policy_type: MultiArmedBandit
  policy_name: PolicyUniformOnVolume
  
mab_ts_bernoulli:
  type: Multigoal
  inherit_from: informed_rrt
  policy_type: MultiArmedBandit
  policy_name: Thomson
  reward_fcn: Bernoulli