controller_list:
  - name: fake_r_robot_controller
    type: $(arg fake_execution_type)
    joints:
      - r_from_X_to_fake
      - r_from_fake_to_Y
  - name: fake_g_robot_controller
    type: $(arg fake_execution_type)
    joints:
      - g_from_X_to_fake
      - g_from_fake_to_Y
  - name: fake_b_robot_controller
    type: $(arg fake_execution_type)
    joints:
      - b_from_X_to_fake
      - b_from_fake_to_Y
  - name: fake_k_robot_controller
    type: $(arg fake_execution_type)
    joints:
      - k_from_X_to_fake
      - k_from_fake_to_Y
  - name: fake_planar4robots_controller
    type: $(arg fake_execution_type)
    joints:
      - b_from_X_to_fake
      - b_from_fake_to_Y
      - g_from_X_to_fake
      - g_from_fake_to_Y
      - k_from_X_to_fake
      - k_from_fake_to_Y
      - r_from_X_to_fake
      - r_from_fake_to_Y
initial:  # Define initial robot poses per group
  - group: planar4robots
    pose: planar4robots_square